/*
 * Copyright (c) 2011 Sveriges Television AB <info@casparcg.com>
 *
 * This file is part of CasparCG (www.casparcg.com).
 *
 * CasparCG is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CasparCG is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CasparCG. If not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Julian Waller, julian@superfly.tv
 */
#version 430


layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(rgba16, binding = 0) uniform image2D imgOutput16bit; // Note: this needs to match what it is writing to
layout(rgba8, binding = 1) uniform image2D imgOutput8bit; // Note: this needs to match what it is writing to

/**
 * We want these buffers to use as large a uint as possible, because the larger they are the less likely we are to need to do 2 memory reads per buffer.
 * As memory is wider than a color component is, I asusme that we wont hit that.
 * 16bit feels like a sensible compromise for planar formats.
 */
layout(std430, binding = 2) readonly buffer buffer_plane0
{
    uint bufferInput0[];
};
layout(std430, binding = 3) readonly buffer buffer_plane1
{
    uint bufferInput1[];
};
layout(std430, binding = 4) readonly buffer buffer_plane2
{
    uint bufferInput2[];
};
layout(std430, binding = 5) readonly buffer buffer_plane3
{
    uint bufferInput3[];
};

layout(std430, binding = 6) buffer description_layout
{
    // This must match convert_from_texture_description in device.h
    uint is_16_bit;
    uint frame_width;
    uint frame_height;
//    uint words_per_line;
//    uint key_only;
    uint premultiply;

    uint source_format;

    uint plane0_linewidth;
    uint plane0_depth;

    uint plane1_linewidth;
    uint plane1_depth;
    uint plane1_half_height;

    uint plane2_linewidth;
    uint plane2_depth;
    uint plane2_half_height;

    uint plane3_linewidth;
    uint plane3_depth;
    uint plane3_half_height;
};

vec4 premultiply_pixel(vec4 pixel) {
    return vec4(
    pixel.r * pixel.a,
    pixel.g * pixel.a,
    pixel.b * pixel.a,
    pixel.a
    );
}

void write_pixel(ivec2 coord, vec4 color) {
    if (premultiply > 0) color = premultiply_pixel(color);

    if (is_16_bit > 0) {
        imageStore(imgOutput16bit, coord, color);
    } else {
        imageStore(imgOutput8bit, coord, color);
    }
}

uint read_from_plane(uint planeIndex, uint offset) {
    switch(planeIndex) {
        case 0:
            return bufferInput0[offset];
        case 1:
            return bufferInput1[offset];
        case 2:
            return bufferInput2[offset];
        case 3:
            return bufferInput3[offset];
    }

    return 0;
}

uint read_component(uint planeIndex, uint planeWidth, bool planeHalfHeight, ivec2 coord, bool is_16bit) {

    uint row_offset = coord.y;
    uint col_offset = coord.x;

    // TODO - something here is off..
    if (planeHalfHeight) row_offset /= 2; // Future: interpolation?
    if (planeWidth < frame_width) col_offset /= 2;  // Future: interpolation?

    // TODO - handle >8bit

    // Future: should this interpolate?
    uint value_index = col_offset % 4;
    uint byte_offset = (row_offset * planeWidth + col_offset) / 4;

    uint shift = value_index * 8;

    return (read_from_plane(planeIndex, byte_offset) >> shift) & 0xff;
}

// Input expects to be floats containing 8bit values (0-255). for higher depths, scale them to be in the range of 8 first
vec4 ycbcra_to_rgba(uint Y, uint Cb, uint Cr, uint A)
{
    const float luma_coefficient = 255.0/219.0;
    const float chroma_coefficient = 255.0/224.0;

    const mat3 color_matrix = mat3(1.0, 0.0, 1.5748, 1.0, -0.1873, -0.4681, 1.0, 1.8556, 0.0); // TODO - non 709 values

    vec3 YCbCr = vec3(float(Y), float(Cb), float(Cr));
    YCbCr -= vec3(16.0, 128.0, 128.0);
    YCbCr *= vec3(luma_coefficient, chroma_coefficient, chroma_coefficient);

    return vec4(YCbCr * color_matrix / 255, A / 255.0);//.bgra;
}

void main() {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);

    // TODO - assumes ycbcr 8bit for now

    // TODO - half height planes?
    // TODO - more general subsampling?
    uint luma = read_component(0, plane0_linewidth, false, texelCoord, plane0_depth > 0);
    uint cb = read_component(1, plane1_linewidth, plane1_half_height > 0, texelCoord, plane1_depth > 0);
    uint cr = read_component(2, plane2_linewidth, plane2_half_height > 0, texelCoord, plane2_depth > 0);

    vec4 value = ycbcra_to_rgba(luma, cb, cr, 255);

    write_pixel(texelCoord, value);
}