/*
 * Copyright (c) 2011 Sveriges Television AB <info@casparcg.com>
 *
 * This file is part of CasparCG (www.casparcg.com).
 *
 * CasparCG is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CasparCG is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CasparCG. If not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Julian Waller, julian@superfly.tv
 */
#version 430


layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(rgba16, binding = 0) uniform image2D imgOutput16bit; // Note: this needs to match what it is writing to
layout(rgba8, binding = 1) uniform image2D imgOutput8bit; // Note: this needs to match what it is writing to

layout(std430, binding = 2) readonly buffer buffer_layout
{
    uint bufferInput[];
};

layout(std430, binding = 3) buffer description_layout
{
    // This must match convert_from_texture_description in device.h
    uint is_16_bit;
    uint frame_width;
    uint frame_height;
//    uint words_per_line;
//    uint key_only;
    uint premultiply;

    uint source_format;

    uint plane0_offset;

    uint plane1_offset;

    uint plane2_offset;

    uint plane3_offset;
};

vec4 premultiply_pixel(vec4 pixel) {
    return vec4(
    pixel.r * pixel.a,
    pixel.g * pixel.a,
    pixel.b * pixel.a,
    pixel.a
    );
}

void write_pixel(ivec2 coord, vec4 color) {
    if (premultiply > 0) color = premultiply_pixel(color);

    if (is_16_bit > 0) {
        imageStore(imgOutput16bit, coord, color);
    } else {
        imageStore(imgOutput8bit, coord, color);
    }
}

void main() {
    vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);



    value.r = ((bufferInput[gl_GlobalInvocationID.x] >> 24) & 0xff) / 255.0;
    value.g = ((bufferInput[gl_GlobalInvocationID.x] >> 16) & 0xff) / 255.0;
    value.b = ((bufferInput[gl_GlobalInvocationID.x] >> 8) & 0xff) / 255.0;

//    value.r = float(texelCoord.x)/(gl_NumWorkGroups.x);
//    value.g = float(texelCoord.y)/(gl_NumWorkGroups.y);

    write_pixel(texelCoord, value);
}