#! /bin/bash

source $(dirname "$0")/image-versions

GIT_HASH=$(git rev-parse --verify --short HEAD)

docker build -t casparcg/server \
  --build-arg GIT_HASH="$GIT_HASH" \
  --build-arg IMAGE_BASE="$IMAGE_BASE" \
  --build-arg IMAGE_CEF="$IMAGE_CEF" \
  --build-arg IMAGE_BOOST="$IMAGE_BOOST" \
  --build-arg IMAGE_FFMPEG="$IMAGE_FFMPEG" \
	-f $PWD/tools/linux/Dockerfile $PWD

