#!/bin/bash

source $(dirname "$0")/image-versions

docker build -t $IMAGE_BASE tools/linux/base
docker build -t $IMAGE_CEF tools/linux/cef
docker build -t $IMAGE_BOOST tools/linux/boost
docker build -t $IMAGE_FFMPEG tools/linux/ffmpeg
